$(function(){$(".menu,.menu-search").click(function(){$("#css-menu").css({right:"0"});$("#page_content").css({margin:"0 340px 0 -340px"})});$(".close-menu").click(function(){$("#css-menu").css({right:"-340px"});$('#search').hide('slow');$("#page_content").css({margin:"0"})});$('.menu-search').click(function(){$('#search').show()})});
$("#cssmenu ul ul li:odd").addClass("odd");$("#cssmenu ul ul li:even").addClass("even");$("#cssmenu > ul > li > a").click(function(){$("#cssmenu li").removeClass("active");$(this).closest("li").addClass("active");var e=$(this).next();if(e.is("ul")&&e.is(":visible")){$(this).closest("li").removeClass("active");e.slideUp("normal")}if(e.is("ul")&&!e.is(":visible")){$("#cssmenu ul ul:visible").slideUp("normal");e.slideDown("normal")}if($(this).closest("li").find("ul").children().length==0){return true}else{return false}});
$('a,img,img.related-post-item-thumbnail,a.related-post-item-title,span.homekompi a,.authorphoto,blockquote,pre,.ringMenu ul li.main,.ringMenu ul li.main2,.ringMenu ul li a span,.credit-link a,input.search-field,i.klik-url').not('.paginator,.paginator span a,a.related-post-item-titleimg,.post-body .separator a,.ringMenu ul li a').attr('rel', 'tooltip');
$('.post-body .separator a,.ringMenu ul li a').data("title", $('.post-body .separator a,.ringMenu ul li a').attr("title")).removeAttr("title");
$('blockquote,pre').attr('title', 'Double click to select all text!');$('i.klik-url').attr('title', 'Click to block text!');
$(document).ready(function(){var e=$("[rel~=tooltip]"),t=false,n=false,r=false;e.bind("mouseenter",function(){t=$(this);tip=t.attr("title");n=$('<div id="tooltip"></div>');if(!tip||tip=="")return false;t.removeAttr("title");n.css("opacity",0).html(tip).appendTo("body");var e=function(){if($(window).width()<n.outerWidth()*1.5)n.css("max-width",$(window).width()/2);else n.css("max-width",340);var e=t.offset().left+t.outerWidth()/2-n.outerWidth()/2,r=t.offset().top-n.outerHeight()-20;if(e<0){e=t.offset().left+t.outerWidth()/2-20;n.addClass("left")}else n.removeClass("left");if(e+n.outerWidth()>$(window).width()){e=t.offset().left-n.outerWidth()+t.outerWidth()/2+20;n.addClass("right")}else n.removeClass("right");if(r<0){var r=t.offset().top+t.outerHeight();n.addClass("top")}else n.removeClass("top");n.css({left:e,top:r}).animate({top:"+=10",opacity:.9},50)};e();$(window).resize(e);var r=function(){n.animate({top:"-=10",opacity:0},50,function(){$(this).remove()});t.attr("title",tip)};t.bind("mouseleave",r);n.bind("click",r)})});
(function(e,t,n,r,i,s,o){e["GoogleAnalyticsObject"]=i;e[i]=e[i]||function(){(e[i].q=e[i].q||[]).push(arguments)},e[i].l=1*new Date;s=t.createElement(n),o=t.getElementsByTagName(n)[0];s.async=1;s.src=r;o.parentNode.insertBefore(s,o)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-60108787-1","auto");ga("send","pageview");
var disqus_shortname="sederettutorial";(function(){var e=document.createElement("script");e.async=false;e.type="text/javascript";e.src="//"+disqus_shortname+".disqus.com/count.js";(document.getElementsByTagName("HEAD")[0]||document.getElementsByTagName("BODY")[0]).appendChild(e)})();
$("img").each(function(){$(this).attr("data-src",$(this).attr("src"));$(this).attr("src","data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=")});
var imgDefer=document.getElementsByTagName("img");for(var i=0;i<imgDefer.length;i++){if(imgDefer[i].getAttribute("data-src")){imgDefer[i].setAttribute("src",imgDefer[i].getAttribute("data-src"))}};

setTimeout(function(){$(".yllix-ads").each(function(){$(this).replaceWith('<iframe class="yllix-ads loader" src="'+$(this).data("src")+'" frameborder="0" scrolling="no" width="300" height="50" marginwidth="0" marginheight="0"></iframe>')})},200);
$(document).ready(function(c){$('#close-yllix').on('click',function(c){$('#adsmobile').fadeOut('slow');});})
